admin:
    path: /
    controller: App\Controller\AdminController::dashboard

# Users
user_delete:
    path: /user/delete/{id}
    controller: App\Controller\UserController::delete

# Pages    
page_form:
    path: /page/{id}
    controller: App\Controller\PageController::form
    defaults: 
        id: null

page_delete:
    path: /page/delete/{id}
    controller: App\Controller\PageController::delete