admin:
    path: /
    controller: App\Controller\AdminController::dashboard

user_delete:
    path: /user/delete/{id}
    controller: App\Controller\UserController::delete
    
page_form:
    path: /page/{id}
    controller: App\Controller\PageController::form
    defaults: 
        id: null
page_delete:
    path: /page/delete/{id}
    controller: App\Controller\PageController::delete

module_form:
    path: /module/{id}
    controller: App\Controller\ModuleController::form
    defaults: 
        id: null
module_delete:
    path: /module/delete/{id}
    controller: App\Controller\ModuleController::delete

input_show:
    path: /input/show/{id}
    controller: App\Controller\PartialController::input
    defaults: 
        id: null
input_form:
    path: /input/{id}
    controller: App\Controller\InputController::form
    defaults: 
        id: null
input_delete:
    path: /input/delete/{id}
    controller: App\Controller\InputController::delete
    
variable_delete:
    path: /variable/delete/{id}
    controller: App\Controller\VariableController::delete