api_posts:
    path: /posts
    controller: App\Controller\ApiController::posts
api_post:
    path: /post/{id}
    controller: App\Controller\ApiController::post
api_users:
    path: /users
    controller: App\Controller\ApiController::users
api_user:
    path: /user/{id}
    controller: App\Controller\ApiController::user
    