post:
    path: /post/{slug}
    controller: App\Controller\PostController::show
post_delete:
    path: /delete/{slug}
    controller: App\Controller\PostController::delete

post_edit:
    path: /edit/{slug}
    controller: App\Controller\PostController::edit

article_form:
    path: /article/{slug}
    controller: App\Controller\ArticleController::form
    defaults:
        slug: null
        
link_form:
    path: /link/{slug}
    controller: App\Controller\LinkController::form
    defaults:
        slug: null

upload:
    path: /upload
    controller: App\Controller\PostController::upload

message:
    path: /message/{slug} # slug of post
    controller: App\Controller\MessageController::new
message_delete:
    path: /message/{slug}/delete/{id}
    controller: App\Controller\MessageController::delete