index:
   path: /
   controller: App\Controller\AppController::index

markdownify:
   path: /markdownify
   controller: App\Controller\ApiController::markdownify
   
cookies:
   path: /cookies
   controller: App\Controller\AppController::cookies

assets_css:
   path: /assets/css
   controller: App\Controller\AssetsController::css
assets_js:
   path: /assets/js
   controller: App\Controller\AssetsController::js 
   

routing_post:
   resource: 'routes/post.yaml'
routing_user:
   resource: 'routes/user.yaml'
routing_api:
   prefix: '/api'
   resource: 'routes/api.yaml'
routing_admin:
   prefix: '/admin'
   resource: 'routes/admin.yaml'

sitemap:
   path: /sitemap
   controller: App\Controller\SitemapController::sitemap

page:
   path: /{url}
   controller: App\Controller\PageController::show 